kind: Service
apiVersion: v1
metadata:
  name: flight-schedule-service
  namespace: flight-ns
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: flight-schedule

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-schedule-deployment
  namespace: flight-ns
  labels:
    app: flight-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-schedule
      track: stable
  template:
    metadata:
      labels:
        app: flight-schedule
        track: stable
    spec:
      containers:
      - name: flight-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
